sudo: required
services:
    - docker

before_install:
    - docker build -t carlosrodrigues/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true carlosrodrigues/docker-react npm run test
